### ISSUE TITLE
Windows 11 – readSGLX "Int Overflow"

### ISSUE THREAD

**Issue by rahim-hashim** [jenniferColonell/SpikeGLX_Datafile_Tools#2]
I've noticed different results on Windows 10/11 and macOS when you run readSGLX.py, particularly on line 340 when generating `tDat` which is an array of sample times for a given .bin file.

![Screenshot 2023-11-01 at 8 24 02 PM](https://github.com/jenniferColonell/SpikeGLX_Datafile_Tools/assets/3630041/5231df21-379d-4123-b67f-8d6dcfcba6aa)

It is a reported issue ([StackOverflow 1970680](https://stackoverflow.com/questions/1970680/integer-overflow-in-numpy-arrays)) that `np.arange` handles integer overflows differently on different operating systems. 

On Windows 11, the output provides negative values for large numbers (as is the case for very large datasets):

![Screenshot 2023-11-02 170646](https://github.com/jenniferColonell/SpikeGLX_Datafile_Tools/assets/3630041/ef001d74-5f7d-47e6-a5c2-64c63306a495)

On macOS Sonoma Version 14.0, the output is as expected:
<img width="487" alt="Screenshot 2023-11-02 at 5 17 11 PM" src="https://github.com/jenniferColonell/SpikeGLX_Datafile_Tools/assets/3630041/ba0733ca-3a10-46ec-b791-e27e67915e9d">

It is possibly because Windows 10/11 defaults np.arange output to 'int34', which is not able to handle such large values. This may cause lots of downstream problems if you want to utilize tDat in any capacity.

To fix, simply add the following `np.arange(firstSamp, lastSamp+1, dtype='int64')`.

**Comment by jenniferColonell** [comment]
sorry it took me so long to get this fixed! I've changed the code as you suggested.
