### ISSUE TITLE
Incorrect AP gain for probeType 2013 (4 shank 2.0)?

### ISSUE THREAD

**Issue by guptadivyansh** [jenniferColonell/SpikeGLX_Datafile_Tools#3]
The AP gain for 2.0 probes is hardcoded [here](https://github.com/jenniferColonell/SpikeGLX_Datafile_Tools/blob/4b6c28658b715808e4941e43d5fa0c57198b09da/Python/DemoReadSGLXData/readSGLX.py#L166C18-L166C18)  to be 80 for probe types 21 and 24. However, the manual for commercial 2.0 says the Gain is 100, and I also see that `imChan0apGain=100` in my recordings with `imDatPrb_type=2013`.

Did the gain change between the test and commercial versions?

**Comment by jenniferColonell** [comment]
Yes, the gain changed between the test and commercial versions. I need to update the Datafile tools, thank you for the reminder!

From: Divyansh Gupta ***@***.***>
Sent: Tuesday, December 12, 2023 12:41 PM
To: jenniferColonell/SpikeGLX_Datafile_Tools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jenniferColonell/SpikeGLX_Datafile_Tools] Incorrect AP gain for probeType 2013 (4 shank 2.0)? (Issue #3)

External Email: Use Caution


The AP gain for 2.0 probes is hardcoded here<https://urldefense.com/v3/__https:/github.com/jenniferColonell/SpikeGLX_Datafile_Tools/blob/4b6c28658b715808e4941e43d5fa0c57198b09da/Python/DemoReadSGLXData/readSGLX.py*L166C18-L166C18__;Iw!!Eh6p8Q!CFtcZnpEZF80EUbb8Muu3O0voXNl930hdSPDtrawc5VG5f0kKc5HJ0mQMrDeMt_CRGl9ASoaDyaiRQvaxwJOA0VacRTotg$> to be 80 for probe types 21 and 24. However, the manual for commercial 2.0 says the Gain is 100, and I also see that imChan0apGain=100 in my recordings with imDatPrb_type=2013.

Did the gain change between the test and commercial versions?

**Comment by guptadivyansh** [comment]
Thanks for the quick reply!

Is it safe to rely on `meta['imChan0apGain']` across 2.0 probe types? I'm fixing a similar issue in[ spikeinterface/neo ](https://github.com/NeuralEnsemble/python-neo/pull/1363#issuecomment-1852564877)

**Comment by jenniferColonell** [comment]
Yes, for any new data, you can use that metadata item. I’ll add that to Datafile tools, too – but I also need to keep them backward compatible.
